# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connectme.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connectme.proto',
  package='connectme',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63onnectme.proto\x12\tconnectme\"\x18\n\x08\x46ilePath\x12\x0c\n\x04path\x18\x01 \x01(\t\")\n\x0c\x46ileChecksum\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0b\n\x03sum\x18\x02 \x01(\t\"8\n\tFileChunk\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"5\n\tPutReturn\x12\x13\n\x0btotal_files\x18\x01 \x01(\x04\x12\x13\n\x0btotal_bytes\x18\x02 \x01(\x04\"\x10\n\x0eVersionRequest\"/\n\x0fVersionResponse\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\"H\n\rLaunchRequest\x12\x13\n\x0bwillconnect\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x03(\t\"\x10\n\x0eLaunchResponse\"}\n\x0b\x43onnectData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12&\n\x07\x63hannel\x18\x02 \x01(\x0e\x32\x15.connectme.DataStream\x12&\n\x04\x63trl\x18\x03 \x01(\x0e\x32\x18.connectme.ControlSignal\x12\x10\n\x08\x65xitcode\x18\x04 \x01(\x05*F\n\rControlSignal\x12\t\n\x05NOSIG\x10\x00\x12\x07\n\x03\x45OF\x10\x01\x12\x08\n\x04\x45XIT\x10\x02\x12\n\n\x06SIGINT\x10\x03\x12\x0b\n\x07SIGKILL\x10\x04*=\n\nDataStream\x12\x0c\n\x08NOSTREAM\x10\x00\x12\t\n\x05STDIN\x10\x01\x12\n\n\x06STDOUT\x10\x02\x12\n\n\x06STDERR\x10\x03\x32\xf9\x01\n\x0b\x46ileManager\x12<\n\x08\x43hecksum\x12\x13.connectme.FilePath\x1a\x17.connectme.FileChecksum(\x01\x30\x01\x12\x33\n\x03Put\x12\x14.connectme.FileChunk\x1a\x14.connectme.PutReturn(\x01\x12\x34\n\x03Get\x12\x13.connectme.FilePath\x1a\x14.connectme.FileChunk(\x01\x30\x01\x12\x41\n\x0cSendChecksum\x12\x14.connectme.FileChunk\x1a\x17.connectme.FileChecksum(\x01\x30\x01\x32Q\n\x0bMetaManager\x12\x42\n\x07Version\x12\x19.connectme.VersionRequest\x1a\x1a.connectme.VersionResponse\"\x00\x32\x8e\x01\n\x0e\x43onsoleManager\x12=\n\x06Launch\x12\x18.connectme.LaunchRequest\x1a\x19.connectme.LaunchResponse\x12=\n\x07\x43onnect\x12\x16.connectme.ConnectData\x1a\x16.connectme.ConnectData(\x01\x30\x01\x62\x06proto3')
)

_CONTROLSIGNAL = _descriptor.EnumDescriptor(
  name='ControlSignal',
  full_name='connectme.ControlSignal',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOSIG', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EOF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGINT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGKILL', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=498,
  serialized_end=568,
)
_sym_db.RegisterEnumDescriptor(_CONTROLSIGNAL)

ControlSignal = enum_type_wrapper.EnumTypeWrapper(_CONTROLSIGNAL)
_DATASTREAM = _descriptor.EnumDescriptor(
  name='DataStream',
  full_name='connectme.DataStream',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOSTREAM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDOUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDERR', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=570,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_DATASTREAM)

DataStream = enum_type_wrapper.EnumTypeWrapper(_DATASTREAM)
NOSIG = 0
EOF = 1
EXIT = 2
SIGINT = 3
SIGKILL = 4
NOSTREAM = 0
STDIN = 1
STDOUT = 2
STDERR = 3



_FILEPATH = _descriptor.Descriptor(
  name='FilePath',
  full_name='connectme.FilePath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='connectme.FilePath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=54,
)


_FILECHECKSUM = _descriptor.Descriptor(
  name='FileChecksum',
  full_name='connectme.FileChecksum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='connectme.FileChecksum.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sum', full_name='connectme.FileChecksum.sum', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=97,
)


_FILECHUNK = _descriptor.Descriptor(
  name='FileChunk',
  full_name='connectme.FileChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='connectme.FileChunk.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='connectme.FileChunk.counter', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='connectme.FileChunk.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=155,
)


_PUTRETURN = _descriptor.Descriptor(
  name='PutReturn',
  full_name='connectme.PutReturn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_files', full_name='connectme.PutReturn.total_files', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bytes', full_name='connectme.PutReturn.total_bytes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=210,
)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='connectme.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=228,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='connectme.VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='connectme.VersionResponse.major', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='connectme.VersionResponse.minor', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=277,
)


_LAUNCHREQUEST = _descriptor.Descriptor(
  name='LaunchRequest',
  full_name='connectme.LaunchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='willconnect', full_name='connectme.LaunchRequest.willconnect', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='connectme.LaunchRequest.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='connectme.LaunchRequest.arguments', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=351,
)


_LAUNCHRESPONSE = _descriptor.Descriptor(
  name='LaunchResponse',
  full_name='connectme.LaunchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=369,
)


_CONNECTDATA = _descriptor.Descriptor(
  name='ConnectData',
  full_name='connectme.ConnectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='connectme.ConnectData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='connectme.ConnectData.channel', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctrl', full_name='connectme.ConnectData.ctrl', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exitcode', full_name='connectme.ConnectData.exitcode', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=496,
)

_CONNECTDATA.fields_by_name['channel'].enum_type = _DATASTREAM
_CONNECTDATA.fields_by_name['ctrl'].enum_type = _CONTROLSIGNAL
DESCRIPTOR.message_types_by_name['FilePath'] = _FILEPATH
DESCRIPTOR.message_types_by_name['FileChecksum'] = _FILECHECKSUM
DESCRIPTOR.message_types_by_name['FileChunk'] = _FILECHUNK
DESCRIPTOR.message_types_by_name['PutReturn'] = _PUTRETURN
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
DESCRIPTOR.message_types_by_name['LaunchRequest'] = _LAUNCHREQUEST
DESCRIPTOR.message_types_by_name['LaunchResponse'] = _LAUNCHRESPONSE
DESCRIPTOR.message_types_by_name['ConnectData'] = _CONNECTDATA
DESCRIPTOR.enum_types_by_name['ControlSignal'] = _CONTROLSIGNAL
DESCRIPTOR.enum_types_by_name['DataStream'] = _DATASTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilePath = _reflection.GeneratedProtocolMessageType('FilePath', (_message.Message,), dict(
  DESCRIPTOR = _FILEPATH,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.FilePath)
  ))
_sym_db.RegisterMessage(FilePath)

FileChecksum = _reflection.GeneratedProtocolMessageType('FileChecksum', (_message.Message,), dict(
  DESCRIPTOR = _FILECHECKSUM,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.FileChecksum)
  ))
_sym_db.RegisterMessage(FileChecksum)

FileChunk = _reflection.GeneratedProtocolMessageType('FileChunk', (_message.Message,), dict(
  DESCRIPTOR = _FILECHUNK,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.FileChunk)
  ))
_sym_db.RegisterMessage(FileChunk)

PutReturn = _reflection.GeneratedProtocolMessageType('PutReturn', (_message.Message,), dict(
  DESCRIPTOR = _PUTRETURN,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.PutReturn)
  ))
_sym_db.RegisterMessage(PutReturn)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREQUEST,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.VersionRequest)
  ))
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONRESPONSE,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.VersionResponse)
  ))
_sym_db.RegisterMessage(VersionResponse)

LaunchRequest = _reflection.GeneratedProtocolMessageType('LaunchRequest', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHREQUEST,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.LaunchRequest)
  ))
_sym_db.RegisterMessage(LaunchRequest)

LaunchResponse = _reflection.GeneratedProtocolMessageType('LaunchResponse', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHRESPONSE,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.LaunchResponse)
  ))
_sym_db.RegisterMessage(LaunchResponse)

ConnectData = _reflection.GeneratedProtocolMessageType('ConnectData', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTDATA,
  __module__ = 'connectme_pb2'
  # @@protoc_insertion_point(class_scope:connectme.ConnectData)
  ))
_sym_db.RegisterMessage(ConnectData)



_FILEMANAGER = _descriptor.ServiceDescriptor(
  name='FileManager',
  full_name='connectme.FileManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=634,
  serialized_end=883,
  methods=[
  _descriptor.MethodDescriptor(
    name='Checksum',
    full_name='connectme.FileManager.Checksum',
    index=0,
    containing_service=None,
    input_type=_FILEPATH,
    output_type=_FILECHECKSUM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='connectme.FileManager.Put',
    index=1,
    containing_service=None,
    input_type=_FILECHUNK,
    output_type=_PUTRETURN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='connectme.FileManager.Get',
    index=2,
    containing_service=None,
    input_type=_FILEPATH,
    output_type=_FILECHUNK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendChecksum',
    full_name='connectme.FileManager.SendChecksum',
    index=3,
    containing_service=None,
    input_type=_FILECHUNK,
    output_type=_FILECHECKSUM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILEMANAGER)

DESCRIPTOR.services_by_name['FileManager'] = _FILEMANAGER


_METAMANAGER = _descriptor.ServiceDescriptor(
  name='MetaManager',
  full_name='connectme.MetaManager',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=885,
  serialized_end=966,
  methods=[
  _descriptor.MethodDescriptor(
    name='Version',
    full_name='connectme.MetaManager.Version',
    index=0,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METAMANAGER)

DESCRIPTOR.services_by_name['MetaManager'] = _METAMANAGER


_CONSOLEMANAGER = _descriptor.ServiceDescriptor(
  name='ConsoleManager',
  full_name='connectme.ConsoleManager',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=969,
  serialized_end=1111,
  methods=[
  _descriptor.MethodDescriptor(
    name='Launch',
    full_name='connectme.ConsoleManager.Launch',
    index=0,
    containing_service=None,
    input_type=_LAUNCHREQUEST,
    output_type=_LAUNCHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='connectme.ConsoleManager.Connect',
    index=1,
    containing_service=None,
    input_type=_CONNECTDATA,
    output_type=_CONNECTDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONSOLEMANAGER)

DESCRIPTOR.services_by_name['ConsoleManager'] = _CONSOLEMANAGER

# @@protoc_insertion_point(module_scope)
